// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.6.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `add_client`, `get_certificate`, `run_connection`

Future<String?> getFingerprint({required String path}) =>
    RustLib.instance.api.crateApiLanMouseServerGetFingerprint(path: path);

Future<void> connect(
        {required String basePath,
        required String ipAddSrt,
        required int port}) =>
    RustLib.instance.api.crateApiLanMouseServerConnect(
        basePath: basePath, ipAddSrt: ipAddSrt, port: port);
